### ISSUE TITLE
Page templates

### ISSUE THREAD

**Issue by Tenesh** [codcax/codlab#10]
### Description

Template design of page.  The list of components should be reusable for general pages and course pages.

### Task List
- [x] Create template React components
- [x] Create sample Page.
- [x] Create sample Course Page.

#### List of reusable template components for Page
- [x] Page layout
- [x] Navigation Bar

#### List of reusable template components for Course
- [x] Course layout
- [x] Sidebar

#### List of reusable general  template components
- [x] Typography (Heading, Paragraph)
- [x] List (Container)
- [x] Hero
- [x] Disclaimer
- [x] Code Editor (no editable)
- [x] Card
- [x] Image
- [x] Blockquote
