### ISSUE TITLE
Templates library package

### ISSUE THREAD

**Issue by Tenesh** [codcax/codlab#11]
### Description

Currently, `Codlab` consist of learning materials in a blog concept which indicates reuse of static components. These components shall be broken down into minor items that shall be reusable and kept similar as templates.

Since there shall be possible templates as parent and child components, it will bloat the app and leads to complex imports of modules / methods throughout the app. We shall proceed to separate these templates namely that could be always reused in most of static pages as NPM package which is more like a `React Component Library`.

#### Package scope / requirements:

1. Only utilize React Nodes as exportable Element or Component.
2. Each component shall cater to the design of `Codlab` templates.
3. Each component shall be able to utilize `tailwindcss` classes or custom classes.
4. Modularity / Customizability of component shall inherit default React HTML props for HTML tags.

#### Task list:

- [ ] Create a NPM package project.
- [ ]  Define requirements and scope of project.
- [ ] Create GitHub repo for project.

**Comment by cod-cax** [comment]
@Tenesh seems like a viable step, but we need to address the default templates and complexity of each component designs and feature before implementing the request. Possibly, we continue with current way and look into this once we have a concrete sample working components. 

At this point, this is too vague without any UI designs. We could create mockup design of components in `Figma` and tailor each component's scope as first step and then proceed with isolating into a NPM package. It wouldn't make sense to create NPM package if there are only less than 10 reusable components.

It would also make sense to look into leveraging existing `React Component Libraries` and think as we could extend those.

**Comment by Tenesh** [comment]
We can leverage `MUI` since it kind of production state of art baked library and we can just use that in `Codlab` rather than extending it into another package.  

I will develop the basic templates as components and compile the scope of each component. At the same time, will test out `MUI` library without extending into another package.

**Comment by Tenesh** [comment]
@cod-cax , we could close this issue once we have combined component templates with `index.tsx `file for each main folder and export the functions from there itself.

**Comment by Tenesh** [comment]
Issue will closed due to lower importance and not required at the current moment.
