### ISSUE TITLE
Setup Webpack

### ISSUE THREAD

**Issue by cod-cax** [codcax/codlab#3]
### Description

Configure Webpack for project with `production` and `development` settings.

### Task List
- [x] Add Webpack package
- [x] Add dependencies and configure module rules.
- [x] Set up environment configs.

**Comment by Tenesh** [comment]
`Webpack` has been set up together with `eslint` and `prettier` . Closing the ticket now, and feel free to reopen once env configuration are planned for deployment.

Commit ID: 9e830fd66e385da420798bf43677d2cf924ddda6
